from django.urls import path
from . import views
from .views_dashboard import (
    WalletBalanceView,
    ProposalStatsView,
    UnreadMessagesView,
    ProjectStatsView,
    PortfolioLimitedView,
    RecentActivityView,
)
from .views import (
    ProjectListCreateView,
    ProjectDetailView,
    ProposalCreateView,
    ProposalListView,
    ProjectMessageCreateView,
    ProjectMessageListView,
    PortfolioDetailView,
    PortfolioListCreateView,
    hire_proposal_view,
    reject_proposal_view,
    project_mark_completed_view,
    RatingListView,
    UserRatingsView,
    mark_project_messages_read,
    dashboard_view
)

urlpatterns = [
    path("projects/", ProjectListCreateView.as_view()),
    path("projects/", ProjectListCreateView.as_view(), name="project-list"),
    path("projects/<int:pk>/", ProjectDetailView.as_view()),
    path('dashboard/', dashboard_view, name='dashboard'),
    path("projects/create/", views.project_create_view, name="project-create"),
    path("projects/<int:project_id>/proposals/", ProposalListView.as_view()),
    path("proposals/create/", ProposalCreateView.as_view()),
    path("projects/<int:project_id>/user_messages/", ProjectMessageListView.as_view()),
    path("user_messages/create/", ProjectMessageCreateView.as_view()),
    path("proposals/", views.proposal_create_view, name="proposal-create"),
    path("proposals/mine/", views.MyProposalsListView.as_view()),
    path("proposals/<int:proposal_id>/hire/", hire_proposal_view),
    path("proposals/<int:proposal_id>/reject/", reject_proposal_view),
    path("projects/<int:project_id>/complete/", project_mark_completed_view),
    path("portfolio/", PortfolioListCreateView.as_view(), name='portfolio-list-create'),
    path("portfolio/<int:pk>/", PortfolioDetailView.as_view(), name='portfolio-detail'),
    path("wallet/balance/", WalletBalanceView.as_view()),
    path("proposals/stats/", ProposalStatsView.as_view()),
    path("messages/unread/", UnreadMessagesView.as_view()),
    path("projects/my-stats/", ProjectStatsView.as_view()),
    path("portfolio/limited/", PortfolioLimitedView.as_view()),   
    path("activities/recent/", RecentActivityView.as_view()),
    path("proposals/<int:proposal_id>/hire/", views.hire_proposal_view),
    path("proposals/<int:proposal_id>/reject/", views.reject_proposal_view),
    path("projects/<int:project_id>/mark-completed/", views.project_mark_completed_view),
    path("projects/<int:project_id>/rate/", views.rate_user_view),
    path("ratings/", RatingListView.as_view(), name="ratings-list"),
    path("users/<int:user_id>/ratings/", UserRatingsView.as_view(), name="user-ratings"),
    path("dashboard/stats/", views.dashboard_view, name="dashboard-stats"),
    path("wallet/", views.wallet_balance_view, name="wallet-balance"),
    path("proposals/stats/", views.proposal_stats_view, name="proposal-stats"),
    path("projects/stats/", views.project_stats_view, name="project-stats"),
    path("messages/<int:project_id>/mark-read/", mark_project_messages_read, name="mark-project-messages-read"),

]