# Generated by Django 5.2.8 on 2025-12-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
